company_admin/config/routes.rb
Rails.application.routes.draw do
  
  resources :line_items
  resources :carts
  resources :products
  resources :payments
  resources :orders
  resources :companies do
  resources :products
  resources :orders
  resources :payments
  end
  
 get 'search_products', to:"orders#search"
 get 'signup', to: 'users#new'
 
 get 'login', to: 'sessions#new'
 post 'login', to: 'sessions#create'
 delete 'logout', to: 'sessions#destroy'
 
resources :users, except: [:new]

get "view_sales", to: "companies#sales_info"

 root 'companies#index'

end

company_admin/app/models/payment.rb
class Payment < ActiveRecord::Base
    
  belongs_to :company
  belongs_to :expense
  validates_presence_of :expense_id,:amount, presence: true,  :message => "No puede ir en blanco"  
  
  scope :hoy, -> { where(created_at: Date.today) }
   
  scope :current_week, -> {
     start = Time.zone.now
     where(created_at: start.beginning_of_week..start.end_of_week).order("created_at desc")
     }
  scope :current_month, -> {
     start =Time.zone.now
     where(created_at: start.beginning_of_month..start.end_of_month).order("created_at desc")
     }

end

company_admin/app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
    

  def index
    @payments = Payment.all
    @company = Company.find(params[:company_id])
    
  end

  def new
    @payment = Payment.new
    @company = Company.find(params[:company_id])
  end

  def create
    @payment = Payment.create(payment_params)
  end

  def edit
    @payment = Payment.find(params[:id])
  end

  def update
    @payment = Payment.update(params[:id], payment_params)
  end
  
  
  def destroy
  	@payment = Payment.find(params[:id])
    @payment.destroy
    flash[:notice] = "Product succesfully deleted"
    respond_to do |format|
      format.html { redirect_to payments_path(@company) }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

  
  private
    def payment_params
      params.require(:payment).permit(:amount, :status,:expense_id,:company_id)
    end
    
    
    
end

company_admin/app/views/payments/_pay_row.html.erb
<!-- this partial create list of payments  render in index  -->

<tr id="<%= payment.id %>">
  <td><%= payment.company.name %></td>
  <td><%= payment.expense.name %></td>
  <td><%= number_to_currency(payment.amount, precision: 2) %></td>
    <td><%= payment.created_at %></td>
  <td>
    <%= link_to "Editar", edit_company_payment_path(payment.company_id,payment), remote: true %>
   
  </td>
  <td>
    <%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, :class => 'delete_payment' %> 
  </td>
</tr>

company_admin/app/views/payments/_payment_form.html.erb
<div id="payment-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= title %></h4>
      </div>
      <!-- start rails code here for payment -->
       <%= form_for @payment, remote: true do |f| %>
     
        <div class="modal-body">
          
          <div class="alert alert-danger" role="alert" style="display: none;"></div>
          <div class="form-group">
            <%= f.hidden_field :company_id,:value => params[:company_id], class: "form-control input-lg" %>
          </div>
          <div class="form-group">
             <%= f.collection_select :expense_id, Expense.all, :id, :name, {prompt: "Selecciona el Proveedor"}, {class: "form-control input-lg"} %>
          </div>
          <div class="form-group">
            <%= f.text_field :amount, class: "form-control input-lg", placeholder: "Monto" %>
          </div>

        </div>

        <div class="modal-footer">
          <%= f.submit class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

company_admin/app/views/payments/create.js.erb
<% if @payment.errors.empty? %>
  // add the row to the table, show alert and hide modal
  $('table tbody').prepend(' <%= j render "pay_row", payment: @payment, company_id:@company %>');
  $('.alert-success').html("El pago ha sido creado con éxito").show();
  $('#payment-modal').modal('hide');
<% else %>
  // show first error
  $('.alert').html('<%= @payment.errors.full_messages[0] %>').show();
<% end %>

company_admin/app/views/payments/destroy.js.erb
$('.delete_payment').bind('ajax:success', function() {  
        $(this).closest('tr').fadeOut();
});  

company_admin/app/views/payments/edit.js.erb
<!--  code to modify payment -->

$('<%= j render "payment_form", title: "Modificar Pago" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

company_admin/app/views/payments/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <h1>Payments</h1>
    </div>
  </div>

  <div class="row">
    <div class="alert alert-success" role="alert" style="display: none;"></div>
    <div class="col-sm-10 col-sm-offset-1 text-right">
      <%= link_to "Registrar pago",  new_company_payment_path(@company), remote: true, class: "btn btn-primary" %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <table class="table">
        <thead>
          <tr>
            <th>Company</th>
            <th>Nombre</th>
            <th>Monto</th>
            <th>Fecha</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
            <% @payments.each do |payment| %>
            <%= render "pay_row", payment: payment %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<p>
   <%= link_to "Back to company", companies_path %>
</p>

company_admin/app/views/payments/new.js.erb
$('<%= j render "payment_form", title: "Registro de Pagos" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

company_admin/app/views/payments/update.js.erb
<!-- Update payments and check error  -->

<% if @payment.errors.empty? %>
  // add the row to the table, show alert and hide modal
  $('table tbody tr#<%= @payment.id %>').replaceWith(' <%= j render "pay_row", payment: @payment %>');
  $('.alert-success').html("El pago ha sido modificado con éxito").show();
  $('#payment-modal').modal('hide');
<% else %>
  // show first error
  alert('<%= @payment.errors.full_messages[0] %>');
<% end %>