company_admin/config/routes.rb
Rails.application.routes.draw do
  
  resources :line_items
  resources :carts
  resources :products
  resources :payments
  resources :orders
  resources :companies do
  resources :products
  resources :orders
  resources :payments
  end
  
 get 'search_products', to:"orders#search"
 get 'signup', to: 'users#new'
 
 get 'login', to: 'sessions#new'
 post 'login', to: 'sessions#create'
 delete 'logout', to: 'sessions#destroy'
 
resources :users, except: [:new]

get "view_sales", to: "companies#sales_info"

 root 'companies#index'

end

company_admin/app/models/company.rb
class Company < ActiveRecord::Base
    validates :name, presence: true, length: {minimum: 3, maximum: 50}

     has_many :products
     has_many :orders 
     has_many :payments
     #has_many :payments, :through => :expenses
end

company_admin/app/controllers/companies_controller.rb
class CompaniesController < ApplicationController


def index
	@companies = Company.all

	@today_sales = Order.current_day.sum(:total_price) 
 
end
# this action fire details sales in 
def sales_info
    
    ### Incomes ###
    @orders = Order.current_week
    @today_sales = Order.current_day.sum(:total_price) 
	@week_sales = Order.current_week.sum(:total_price) 
	@month_sales = Order.current_month.sum(:total_price) 
	
	###  Payments,expenses###
	@week_expenses = Payment.current_week
	
end

def payments_info
    
end

def show
	@company = Company.find(params[:id])
#	@company.records.build
end
def new
    @company = Company.new
end
def edit
   @company = Company.find(params[:id]) 
end
def create
    @company = Company.new(company_params)
    if @company.save
        flash[:notice] = "Company was succesfully created"
        redirect_to company_path(@company)
    else
        render 'new'
    end
end
def update
   @company = Company.find(params[:id])
   if @company.update(company_params)
       flash[:notice] = "Company succesfully updated"
       redirect_to company_path(@company)
       else
       render 'edit' 
   end
end
def destroy
    @company = Company.find(params[:id])
    @company.destroy
    flash[:notice] = "Company succesfully deleted"
        redirect_to company_path(@company)
end

private

def company_params
    params.require(:company).permit(:name)
end




end

company_admin/app/views/companies/_form.html.erb
<%= form_for @company do |f| %>

<% if @company.errors.any? %>
<h2>  The following error prevented the company to be created</h2>
  <ul>
    <% @company.errors.full_messages.each do |msg| %>
  <li> <%= msg %></li>
  <% end %>
  </ul>
<% end %>


<p>
    <%= f.label :name %>
    <%= f.text_field :name %>
</p>


<%= f.submit %>

<% end %>
<%= link_to "Back Listing Companies", companies_path %>

company_admin/app/views/companies/_sales_info.html.erb
<div class="sales-table pricing-three-column row">
      
        <div class="plan col-sm-4 col-lg-4">
          <div class="hoy">
            <h3>Hoy</h3>
          </div>
           <h4> <%=number_to_currency(@today_sales )%></h4>
        </div>
        
        <div style="z-index:55;" class="plan col-sm-4 col-lg-4">
          <div class="semana">
            <h3> Semana Actual </h3>
          </div>
           <h4> <%=number_to_currency(@week_sales )%></h4>
        </div>
        
        <div class="plan col-sm-4 col-lg-4">
          <div class="mensual">
            <h3>Mes Actual</h3>
          </div>
           <h4> <%=number_to_currency(@month_sales )%></h4>
        </div>
        
</div>


            <table class="table">
                <thead>
                    <tr>
                        <th>DETALLE</th>
                        <th>INGRESOS</th>
                        <th> TOTAL</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                <% @orders.each do |order| %>
                    <tr id="<%= order.id %>">
                      <td><%=order.total_price %></td>
                      <td><%= link_to order.id, order_path(order), remote: true %> </td>
                      <td><%= number_to_currency(order.total_price, precision: 2) %></td>
                    </tr>
                <% end %>
                </tbody>
                
            </table><!--  close table -->
            
                        <table class="table table-bordered">

                <thead>
                    <tr>                  
                        <th>Ingresos</th>
                        <th>Gastos</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                    <td> <%=number_to_currency(@week_sales )%> </td>
                    <td> <%=number_to_currency(@week_expenses )%> </td>
                    <td>3</td>
                    </tr>                           
                </tbody>
            </table>

company_admin/app/views/companies/_sales_info_modal.html.erb
<div id="sales-info-modal" class="modal fade">
   <div class="modal-dialog">
      <div class="modal-content">
      
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><%= title %></h4>
         </div>
         <!-- render   line_items for (invoice) lineitem/invoice partial -->        
         
         <div class="modal-body">
            <%= render 'sales_info' %>
         </div>
         
         <div class="modal-footer">  </div>
         
      </div>
      <!-- /.modal-content -->
   </div>
   <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

company_admin/app/views/companies/edit.html.erb
<h1> Edit</h1>



<%= render 'form' %>

company_admin/app/views/companies/index.html.erb
<div class="container text-center">
   <h3>Listing  Companies</h3>
   <br>
   
   <div class="row">
      <% 	@companies.each do |company| %>
          <div class="col-sm-4">
             <%= link_to (image_tag "http://placehold.it/150x80?text=IMAGE", :alt =>  "image", :class =>"img-responsive md-image"), company_path(company) %>
             <p> <%= company.name %></p>
             <td><%= link_to 'Delete', company_path(company), method: :delete, data: {confirm: "Are you sure?"} %></td>
          </div>
          
      <% end %> 
      
      <div class="col-sm-4">
         <div class="well">
              <p><%= link_to "Corte Semanal ", view_sales_path, remote: true %> </p>
         </div>
         <div class="well">
                      <p> Ventas de Hoy: <%=number_to_currency(@today_sales )%></p>
         </div>
      </div>
      
   </div>
   
</div>
<br>
<p>
   <%= link_to "Create new company", new_company_path %>
</p>

company_admin/app/views/companies/new.html.erb
<h1> New page </h1>



<%= form_for @company do |f| %>

<% if @company.errors.any? %>
<h2>  The following error prevented the company to be created</h2>
  <ul>
    <% @company.errors.full_messages.each do |msg| %>
  <li> <%= msg %></li>
  <% end %>
  </ul>
<% end %>


<p>
    <%= f.label :name %>
    <%= f.text_field :name %>
</p>


<%= f.submit %>

<% end %>
<%= link_to "Back Listing Companies", companies_path %>

company_admin/app/views/companies/sales_info.js.erb
$('<%= j render "sales_info_modal", title: "Monto de ventas" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

company_admin/app/views/companies/show.html.erb
<div class="container text-center">
  <h1><%= @company.name %></h1><br>
  <div class="row">
    <div class="col-sm-4">
      <%= link_to (image_tag "http://placehold.it/150x80?text=IMAGE", :alt =>  "reg-new-product", :class =>"img-responsive md-image"), new_company_product_path(@company), remote: true %>
      <p><%= link_to " Lista de  productos",company_products_path(@company)  %></p>
      <p>Registrar productos</p>
      
    </div>
    <div class="col-sm-4">
      <%= link_to (image_tag "http://placehold.it/150x80?text=IMAGE", :alt =>  "reg-order", :class =>"img-responsive md-image"), new_company_order_path(@company), remote: true %>
      <p><%= link_to " Lista de  ventas",company_orders_path(@company)  %></p>
      <p>Registrar Ventas </p>
    </div>
    <div class="col-sm-4">
      <%= link_to (image_tag "http://placehold.it/150x80?text=IMAGE", :alt =>  "reg-payments", :class =>"img-responsive md-image"), new_company_payment_path(@company), remote: true %>
           <p><%= link_to " Lista de pagos",company_payments_path(@company)  %></p>
      <p> Pagos </p>
    </div>
  </div>
</div><br>


<div>
  
<%= link_to 'Edit company', edit_company_path(@company) %> |
<%= link_to 'Back ', companies_path %> 
</div>