company_admin/config/routes.rb
Rails.application.routes.draw do
  
  resources :line_items
  resources :carts
  resources :products
  resources :payments
  resources :orders
  resources :companies do
  resources :products
  resources :orders
  resources :payments
  end
  
 get 'search_products', to:"orders#search"
 get 'signup', to: 'users#new'
 
 get 'login', to: 'sessions#new'
 post 'login', to: 'sessions#create'
 delete 'logout', to: 'sessions#destroy'
 
resources :users, except: [:new]

get "view_sales", to: "companies#sales_info"

 root 'companies#index'

end

company_admin/app/models/product.rb
class Product < ActiveRecord::Base
    
    validates :name,:price, presence: true

    belongs_to :company

    has_many :line_items
    has_many :orders, :through => :line_items

 
     before_destroy :ensure_not_referenced_by_any_line_item
     
     


    
def self.search(search)
  # Title is for the above case, the OP incorrectly had 'name'
   where("name LIKE ?", "%#{search}%")
   where("code LIKE ?", "%#{search}%") 
end

   private
 
    # ensure that there are no line items referencing this product
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items present')
        return false
      end
    end
 
    
end

company_admin/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @company = Company.find(params[:company_id])
    
  
  end

  def new
    @product = Product.new
    @company = Company.find(params[:company_id])
  end

  def create
    @product = Product.create(product_params)
    @product.company = Company.first
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.update(params[:id], product_params)
  end
  
  def destroy
  	@product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Product succesfully deleted"
    respond_to do |format|
      format.html { redirect_to products_path(@company) }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end
    
  
  private
    def product_params
      params.require(:product).permit(:code,:name, :price,:quantity,:cost,:description,:image,:company_id)
    end
end

company_admin/app/views/products/_form.html.erb
<div id="product-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= title %></h4>
      </div>
      <!-- start rails code -->
      <%= form_for @product, remote: true do |f| %>
        <div class="modal-body">
          
          <div class="alert alert-danger" role="alert" style="display: none;"></div>
          <div class="form-group">
            <%= f.hidden_field :company_id,:value => params[:company_id], class: "form-control input-lg" %>
          </div>
          <div class="form-group">
            <%= f.text_field :code, class: "form-control input-lg", placeholder: "Codigo del producto" %>
          </div>
          <div class="form-group">
            <%= f.text_field :name, class: "form-control input-lg", placeholder: "nombre" %>
          </div>
          <div class="form-group">
            <%= f.text_field :quantity, class: "form-control input-lg", placeholder: "Cantidad" %>
          </div>
          <div class="form-group">
            <%= f.text_field :cost, class: "form-control input-lg", placeholder: "Costo" %>
          </div>
          <div class="form-group">
            <%= f.text_field :price, class: "form-control input-lg", placeholder: "Precio" %>
          </div>
          <div class="form-group">
            <%= f.text_field :description, class: "form-control input-lg", placeholder: "Description" %>
          </div>


        </div>

        <div class="modal-footer">
          <%= f.submit class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>
      
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

company_admin/app/views/products/_row.html.erb
<tr id="<%= product.id %>">
  <td><%= product.code %></td>
  <td><%= product.company_id %></td>
  <td><%= product.name %></td>
  <td><%= number_to_currency(product.price, precision: 2) %></td>
  <td>
    <%= link_to "Editar", edit_company_product_path(product.company_id, product), remote: true %>
  </td>
  <td>
    <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, :class => 'delete_product' %> 
  </td>
</tr>

company_admin/app/views/products/create.js.erb
<% if @product.errors.empty? %>
  // add the row to the table, show alert and hide modal
  $('table tbody').append(' <%= j render "row", product: @product %>');
  $('.alert-success').html("El producto ha sido creado con éxito").show();
  $('#product-modal').modal('hide');
<% else %>
  // show first error
  alert('<%= @product.errors.full_messages[0] %>');
<% end %>

company_admin/app/views/products/destroy.js.erb
$('.delete_product').bind('ajax:success', function() {  
        $(this).closest('tr').fadeOut();
});  

company_admin/app/views/products/edit.js.erb
$('<%= j render "form", title: "Modificar Producto" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

company_admin/app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <h1>Products</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-10 col-sm-offset-1 text-right">
      <%= link_to "Nuevo Producto",  new_company_product_path(@company), remote: true, class: "btn btn-primary" %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <table class="table">
        <thead>
          <tr>
            <th>Codigo</th>
            <th>Company</th>
            <th>Nombre</th>
            <th>Precio</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
            <% @products.each do |product| %>
            <%= render "row", product: product %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<p>
   <%= link_to "Back to company", companies_path %>
</p>

company_admin/app/views/products/new.js.erb
$('<%= j render "form", title: "Nuevo Producto" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

company_admin/app/views/products/update.js.erb
<% if @product.errors.empty? %>
  // add the row to the table, show alert and hide modal
  $('table tbody tr#<%= @product.id %>').replaceWith(' <%= j render "row", product: @product %>');
  $('.alert-success').html("El producto ha sido modificado con éxito").show();
  $('#product-modal').modal('hide');
<% else %>
  // show first error
  alert('<%= @product.errors.full_messages[0] %>');
<% end %>