company_admin/config/routes.rb
Rails.application.routes.draw do
  
  resources :line_items
  resources :carts
  resources :products
  resources :payments
  resources :orders
  resources :companies do
  resources :products
  resources :orders
  resources :payments
  end
  
 get 'search_products', to:"orders#search"
 get 'signup', to: 'users#new'
 
 get 'login', to: 'sessions#new'
 post 'login', to: 'sessions#create'
 delete 'logout', to: 'sessions#destroy'
 
resources :users, except: [:new]

get "view_sales", to: "companies#sales_info"

 root 'companies#index'

end

company_admin/app/models/order.rb
class Order < ActiveRecord::Base
  
    before_save { self.total_price = total_price }  

  #has_many :products, :through => :line_items
  
  belongs_to :company
  has_many :line_items, :dependent => :destroy
  
  #  use scope  to filter querys in orders
 scope :current_day, -> { where("created_at > ?", Time.zone.today).order("created_at desc") }
 
 scope :current_week, -> {
     start = Time.zone.now
     where(created_at: start.beginning_of_week..start.end_of_week).order("created_at desc")
     }
 scope :current_month, -> {
     start =Time.zone.now
     where(created_at: start.beginning_of_month..start.end_of_month).order("created_at desc")
     }
  #  This method is called  in order controller  action create  to save the items from  cart to lineitems

    def add_line_items_from_cart(cart)
        cart.line_items.each do |item|
          item.cart_id = nil
          line_items << item 
        end
    end
   #   Sum all   items    in lineitems to get the total  of sale
    def total_price
      line_items.to_a.sum { |item| item.total_price }
    end


end

company_admin/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  
  
  def index
    @line_items = LineItem.all
    @company = Company.find(params[:company_id])     
    #@orderss = Order.all.order("created_at DESC").limit(5) 
    
   case  
      when params[:q] ==="all"
          @orders = Order.limit(100).order("created_at DESC").paginate(:page => params[:page],:per_page => 10)
      when params[:q] ==="semanal"
          @orders = Order.current_week.paginate(:page => params[:page], :per_page => 10)
      when params[:q] === "mensual"
          @orders = Order.current_month.paginate(:page => params[:page], :per_page => 10)
      else
          @orders = Order.current_day.paginate(:page => params[:page], :per_page => 10)
   end
  end   
   
  def search
    if params[:search]
      @products = Product.search(params[:search]).order("created_at DESC").limit(2) 
    else
      redirect_to company_path(@company)
    end   
  end

  def new       
    @order = Order.new
    #@company = Company.find(params[:company_id])
    @cart = current_cart 

  end
  
  def show    
    @line_items = LineItem.all
    @order = Order.find(params[:id])
     respond_to do |format|
      format.js
    end
  end
  

  def create
    
   @order = Order.create(order_params)
   @order.add_line_items_from_cart(current_cart)
   
    
   respond_to do |format|
    if @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
       # format.html { redirect_to(orders_url, :notice => 
         # 'Thank you for your order.') }
        #format.xml  { render :xml => @order, :status => :created,
        #  :location => @order }
        format.js
       else
        @cart = current_cart
        
        format.html {redirect_to (companies_path) }#render :action => "new" }
       # format.xml  { render :xml => @order.errors,
         # :status => :unprocessable_entity }
    end
    end
  end


  def destroy
  	@order = Order.find(params[:id])
    if  @order.destroy

    flash[:notice] = "Order succesfully deleted"
    respond_to do |format|
      format.html { redirect_to orders_path(@company) }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
    end
  end
    
  
  private
    def order_params
      params.require(:order).permit(:user_id,:company_id,:check_out_at, :total_price)
    end
end

company_admin/app/views/orders/_invoice_modal.html.erb
<div id="invoice" class="modal fade">
   <div class="modal-dialog">
      <div class="modal-content">
      
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><%= title %></h4>
         </div>
         <!-- render   line_items for (invoice) lineitem/invoice partial -->        
         
         <div class="modal-body">
           <%=render 'line_items/invoice' %>
         </div>
         
         <div class="modal-footer">  </div>
         
      </div>
      <!-- /.modal-content -->
   </div>
   <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

company_admin/app/views/orders/_order_form.html.erb
<div id="order-modal" class="modal fade">
   <div class="modal-dialog">
      <div class="modal-content">
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><%= title %></h4>
         </div>
         <!-- render   product_search_form code  from partial -->
         <%= render 'product_search_form' %> 
         <!-- This code show or hide the cart if empty-->
         <div id="cart">
            <% if @cart %>
            <%= hidden_div_if(@cart.line_items.empty?, :id => 'cart') do %>
            <%= render @cart %>
            <% end %>
            <% end %>
         </div>
         <!-- Order params are hiddden, Use this params to create order and create relationship to invoice
          wich contain  information about company who belongs this sale and the  user who's made it-->
         <%= form_for @order , remote: true do |f| %>
         <div class="modal-body">
            <div class="alert alert-danger" role="alert" style="display: none"> </div>
            <div class="form-group">
               <%= f.hidden_field :user_id,:value => (current_user.id), class: "form-control input-lg" %>
            </div>
            <div class="form-group">
               <%= f.hidden_field :company_id,:value => params[:company_id], class: "form-control input-lg" %>
            </div>
            <div class="form-group">
               <%= f.hidden_field :check_out_at, :value => l(Time.zone.now, format: :short), class: "form-control input-lg" %>
            </div>
            <div class="form-group">
               <%= f.hidden_field :total_price  , :value => (number_to_currency(@cart.total_price)) ,class: "form-control input-lg", placeholder: "TOTAL" %>
            </div>
         </div>
         <div class="modal-footer">
            <%= f.submit "Cobrar",class: "btn order-input btn-primary btn-lg btn-block" %>
         </div>
         <% end %>
      </div>
      <!-- /.modal-content -->
   </div>
   <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

company_admin/app/views/orders/_order_modal.html.erb
<div id="order-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
        </button>
          <h4 class="modal-title"><%= title %></h4>
      </div>
      <!-- start rails code -->
     
        <div class="modal-body">
          <!-- search form -->
          <div class="alert alert-danger" role="alert" style="display: none;"></div>
          


      <%= form_for @order, remote: true do |f| %>

          <div class="form-group">
            <%= f.hidden_field :company_id,:value => params[:user_id], class: "form-control input-lg" %>
          </div>
          <div class="form-group">
            <%= f.hidden_field :user_id,:value => params[:user_id], class: "form-control input-lg" %>
          </div>
          <div class="form-group">
            <%= f.hidden_field :_id,:value => params[:user_id], class: "form-control input-lg" %>
          </div>
          <div class="form-group">
            <%= f.text_field :check_out_at, class: "form-control input-lg", placeholder: "Nombre de Usuario" %>
          </div>
           <div class="form-group">
            <%= f.text_field :total_price, class: "form-control input-lg", placeholder: "Nombre de Usuario" %>
          </div>
        
        
        </div><!-- /.modal-body -->
                
        <div class="modal-footer">
             <%= f.submit  class: "btn btn-primary btn-lg btn-block" %>
        </div>
       <% end %>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

company_admin/app/views/orders/_order_row.html.erb
<tr id="<%= order.id %>">
  <td><%= link_to order.id, order_path(order), remote: true %> </td>
  <td><%= order.check_out_at %></td>
  <td><%= number_to_currency(order.total_price, precision: 2) %></td>
  <td>
    <%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, :class => 'delete_order' %> 
  </td>  
</tr>

company_admin/app/views/orders/_product_search_form.html.erb
<!-- This is a partial  form for search product --> 
<%= form_tag search_products_path, method: :get, remote: true, class: 'product-lookup   ' do %>
<div class="input-group">
   <%= text_field_tag :search, params[:search], 
      placeholder:" Buscar producto ",autofocus: true,
      class: "form-control search-box input-lg" %> 
   <span class="input-group-btn">
   <%= button_tag( type: :submit, class: "btn search btn-lg btn-success") do %>
   <i class="glyphicon glyphicon-search"></i> 
   <% end %>
   </span>
</div>
<% end %>
<!-- This code show results of search and append the results on tbody search.js -->
<div id="product-lookup-results " >
   <table class="table table-search ">
      <thead>
         <tr>
            <th>Codigo</th>
            <th>Descripcion</th>
            <th>Precio</th>
            <th></th>
         </tr>
      </thead>
      <tbody>
      </tbody>
   </table>
</div>
         <!-- The table is hiden by default and  if is not empty  append data  seach.js-->      
         <script>
            //$('.product-lookup').css({"margin-top" : "15px"})
            $('.table-search thead').hide();
         </script> 
   

company_admin/app/views/orders/_row.html.erb
<tr id="<%= product.id %>">
  <td><%= product.code %></td>
  <td><%= product.name %></td>
  <td><%= number_to_currency(product.price, precision: 2) %></td>
  <td>
    <%= button_to 'Agregar al carrito', line_items_path(:product_id => product),
        :remote => true %>
  </td>

</tr>

company_admin/app/views/orders/_search_results.html.erb
 <% @products.each do |product| %>
  <tr id="<%= product.id %>">
    <td><%= product.code %></td>
    <td><%= product.name %></td>
    <td><%= number_to_currency(product.price, precision: 2) %></td>
    <div class="col-md-2">
    <td>
      <%= button_to 'Agregar al carrito', line_items_path(:product_id => product),
          :remote => true %>
    </td> 
    </div>
  </tr>
 <% end %>
               

company_admin/app/views/orders/create.js.erb
<% if @order.errors.empty? %>
  // add the row to the table, show alert and hide modal  check if user has items added
  <% if @order.line_items.blank? %>
    alert(' Tu carrito esta vacio');
    <% else %>
  $('table tbody').prepend(' <%= j render "order_row", order: @order %>');
  $('.alert-success').html("La orden ha sido creado con éxito").show();
  $('#order-modal').modal('hide');
   <% end %>
<% else %>
  // show first error
  alert('<%= @order.errors.full_messages[0] %>');
<% end %>

company_admin/app/views/orders/destroy.js.erb
$('.delete_order').bind('ajax:success', function() {  
        $(this).closest('tr').fadeOut();
});  

company_admin/app/views/orders/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
            <div class="alert alert-success" role="alert" style="display: none;"></div>
            <h1>Ventas</h1>        

        </div>
    </div>

    <div class="row">

        
        <div class="col-sm-10 col-sm-offset-1 text-right">
            <%=link_to "Nuevo order", new_company_order_path(@company), remote: true, class: "btn btn-primary" %>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
          <!--  start scopes links container -->
        <div id="scope-container" > 
          <ul id="scope-list" class="nav nav-tabs">
            <li class="active">
            <%= link_to "RECIENTES ",company_orders_path(q:"actual") %>
            </li>
            <li>
            <%= link_to "SEMANA",company_orders_path(q:"semanal") %>
            </li>
            <li>
            <%= link_to "MES",company_orders_path(q:"mensual") %>
            </li>
            <li>
            <%= link_to "TODO",company_orders_path(@company, q:"all") %>
            </li>
          </ul>          
        </div><!-- end  scopes container -->
          
          <!-- start table for orders use gem paginate-->
            <table class="table">
                <thead>
                    <tr>
                        <th>RECIBO No.</th>
                        <th>FECHA</th>
                        <th> TOTAL</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <% @orders.each do |order| %>
                        <%=render "order_row", order: order %>
                    <% end %>
                </tbody>
            </table><!--  close table -->
             <div  align="center" class="paginate"> <%= will_paginate @orders, renderer: BootstrapPagination::Rails  %></div>

        </div> <!-- close col-sm-10 -->
    </div>

</div><!-- close div container -->
<p>
    <%=link_to "Volver", companies_path %>
</p>

company_admin/app/views/orders/new.js.erb
$('<%= j render "order_form", title: "Registrar Venta" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

company_admin/app/views/orders/search.js.erb
<!--  use jquery val() method to  return a blank text_field as default value -->
$('#search').val("");
$('.table-search tbody ').prepend(' <%= j render "search_results", order: @order %>');
$('.table-search thead').show();

company_admin/app/views/orders/show.js.erb
$('<%= j render "invoice_modal", title: "Orden ##{@order.id}" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();